apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: ml-app
  template:
    metadata:
      name: web-app
      labels:
        app: ml-app
    spec:
      containers:
        - name: app-img
          image: 03piyu/app:v1
          ports:
            - containerPort: 80
